services:
  db:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_ID}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db/data:/var/lib/postgressql/data
  
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 4000:4000
    volumes:
      - ./client/app:/usr/app
      - /usr/app/node_modules

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - 80:80
    depends_on:
      - restserver
      - taskserver

  restserver:
    container_name: restserver
    build:
      context: ./restserver
    ports:
      - 3000:3000
    environment:
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./restserver/app:/usr/app
      - /usr/app/node_modules

  taskserver:
    container_name: taskserver
    build:
      context: ./taskserver
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'
    volumes:
      - ./taskserver/app:/usr/app

  mq:
    container_name: mq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
