services:
  db:
    container_name: db
    build:
      context: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_ID}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./db/data:/var/lib/postgressql/data
  
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 4000:4000
    volumes:
      - ./client/app:/usr/app
      - /usr/app/node_modules
  
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 3000:3000
    environment:
      DB_ID: "${DB_ID}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: ${DB_NAME}"
      DB_HOST: 'db'

    volumes:
      - ./server/app:/usr/app
      - /usr/app/node_modules
  mq:
    container_name: mq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
